cache:
  directories:
    - ~/.npm
    - ~/.rvm/
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - gem install chandler
  - echo Succeeded!
  - bash -x ./3excB.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
